adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('trainings/', adminapp.trainings, name='trainings'),
    path('trainings/create/', adminapp.training_create, name='training_create'),
    path('trainings/update/<int:pk>/', adminapp.training_update, name='training_update'),
    path('trainings/delete/<int:pk>/', adminapp.training_delete, name='training_delete'),

    path('schedules/', adminapp.schedules, name='schedules'),
    path('schedules/create/', adminapp.schedule_create, name='schedule_create'),
    path('schedules/update/<int:pk>/', adminapp.schedule_update, name='schedule_update'),
    path('schedules/delete/<int:pk>/', adminapp.schedule_delete, name='schedule_delete'),

    path('users/read/', adminapp.users, name='users'),
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('progress/', adminapp.progress, name='progress'),
    path('messages/', adminapp.messages, name='messages'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
	path('update/', authapp.update, name='update'),
]    

fitness/urls.py
"""fitness URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:"""

from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('personal/', include('personalapp.urls', namespace='personal')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    #path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.contrib import admin

import mainapp.views as mainapp

app_name = 'main'

urlpatterns = [
    path('', mainapp.gallery, name='index'),
    path('gallery/', mainapp.gallery, name='gallery'),
    path('exercise/', mainapp.exercise, name='exercise'),
    path('diet/', mainapp.diet, name='diet'),
    path('progress/', mainapp.progress, name='progress'),
]

mainapp/models.py
from random import random
import datetime as dt
from django.utils.timezone import now
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.functions import Extract

from authapp.models import FitnessUser 

class Photo(models.Model):
    """ Фото для галереи с автоматическим временем добавления """
    image = models.ImageField(
        upload_to='gallery', 
        null=True, blank=True
        )
    add_datetime = models.DateTimeField(
        verbose_name='время фото',
        auto_now=True
        )

    def __str__(self):
        return self.image.name


class Antropometry(models.Model):
    """ Модель для хранения антропометричесих данных
    по каждому тренирующемуся в определнный момент времени"""
    weight = models.PositiveSmallIntegerField(
        verbose_name=' вес, кг',
        #null=True, blank=True,
        )
    chest = models.PositiveSmallIntegerField(
        verbose_name=' окружность грудной клетки, см',
        #null=True, blank=True,
        )
    abdominal = models.PositiveSmallIntegerField(
        verbose_name=' окружность живота, см',
        #null=True, blank=True,
        )
    biceps = models.PositiveSmallIntegerField(
        verbose_name=' окружность бицепса, см',
        #null=True, blank=True,
        )
    thigh = models.PositiveSmallIntegerField(
        verbose_name=' окружность бедра, см',
        #null=True, blank=True,
        )
    shin = models.PositiveSmallIntegerField(
        verbose_name=' окружность голени, см',
        #null=True, blank=True,
        )
    add_datetime = models.DateTimeField(
        verbose_name='время добавления данных, см',
        #null=True, blank=True,
        )
    fitnessuser = models.ForeignKey(
        FitnessUser, 
        verbose_name = "Ссылка на тренирующегося",
        on_delete=models.CASCADE, 
        #null=True, blank=True
        )
    
    def get_effect(self):
        """ Функция расчета прогресса у тренирующегося"""
        return random.randint(1,10)


class Training(models.Model):
    """ Модель для описания тренировок """
    desc = models.TextField(
        verbose_name="Описание тренировки",
        max_length=1000,
        null=True, blank=True,
    )
    short_desc = models.CharField(
        verbose_name="Короткое описание тренировки",
        max_length=100,
        null=True, blank=True,
    )
    is_active = models.BooleanField(
        verbose_name='активна ли тренировка',
        default=True
    )

    def __str__(self):
        return str(self.short_desc)


class Schedule(models.Model):
    """ Модель для хранения назначенных тренером занятий
    для каждого тренирующегося"""
    date = models.DateField(
        verbose_name='дата посещения тренировки',
        null=True, blank=True
        )
    time = models.TimeField(
        verbose_name='время посещения тренировки',
        null=True, blank=True
    )
    is_visit = models.BooleanField(
        verbose_name='пришел ли на тренировку',
        default=False
        )
    fitnessuser = models.ForeignKey(
        FitnessUser, 
        verbose_name="Ссылка на тренирующегося",
        on_delete=models.CASCADE, 
        null=True, blank=True
        )
    training = models.ForeignKey(
        Training,
        verbose_name="Ссылка на вид тренировки",
        on_delete=models.CASCADE,
        null=True, blank=True
    )

    def __str__(self):
        return f'{self.fitnessuser } { self.date } { self.time } { self.training }'

    def clean(self):
        OPEN, CLOSE = settings.OPENING_HOURS
        print(self.date, now().date())
        if self.date < now().date():
            raise ValidationError('Нельзя запланировать тренировку в прошлом')
        if self.time < dt.time(OPEN) or self.time > dt.time(CLOSE):
            raise ValidationError('Вы указали нерабочее время')


class Message(models.Model):
    """ Модель сообщений для тренера"""
    body = models.TextField(
        verbose_name='Тело сообщения',
        null=True, blank=True,
        max_length=250
    )
    fitnessuser = models.ForeignKey(
        FitnessUser,
        verbose_name="Ссылка на тренирующегося",
        on_delete=models.CASCADE,
        null=True, blank=True
        )
    timestamp = models.DateTimeField(
        verbose_name='датавремя отправки сообщения',
        null=True, blank=True,
    )

    def __str__(self):
        return self.body[:50]


@models.DateField.register_lookup
class ExtractWeek(Extract):
    """  Класс для получения номера недели в запросе с выч полем"""
    lookup_name = 'week'


@models.DateField.register_lookup
class ExtractYear(Extract):
    """  Класс для получения года в запросе с выч полем"""
    lookup_name = 'year'

mainapp/views.py
from django.db.models import Max
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from mainapp.models import Photo, Antropometry


def gallery(request):
    photo_list = Photo.objects.order_by('add_datetime')
    paginator = Paginator(photo_list, 8)
    page = request.GET.get('page', 1)
    try:
        photos = paginator.page(page)
    except PageNotAnInteger:
        photos = paginator.page(1)
    except EmptyPage:
        photos = paginator.page(paginator.num_pages)

    context = {
        'title': 'Галерея фото',
        'photos': photos,
    }
    return render(request, 'mainapp/gallery.html', context)


def exercise(request):
    return render(request, 'mainapp/exercise.html', {'title': 'техника упражнений'})


def diet(request):
    return render(request, 'mainapp/diet.html', {'title': 'питание'})


def progress(request):
    max_abdominal = Antropometry.objects.aggregate(Max('abdominal'))
    winner = Antropometry.objects.filter(abdominal=max_abdominal['abdominal__max']).first()
    context = {
        'title': 'прогресс месяца',
        'winner': winner.fitnessuser,
    }
    return render(request, 'mainapp/progress.html', context)

mainapp/templates/mainapp/includes/inc__main_menu.html
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
        <li class="nav-item {% if request.resolver_match.url_name == 'gallery'%} active {% endif%}">
          <a class="nav-link" href="{% url 'main:gallery'%}">галерея</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'exercise'%} active {% endif%}">
          <a class="nav-link" href="{% url 'main:exercise' %}">техника упражнений</a>
        </li>
        <li class="{% if request.resolver_match.url_name == 'diet'%} active {% endif%}">
          <a class="nav-link" href="{% url 'main:diet'%}">питание</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'progress'%} active {% endif%}">
          <a class="nav-link" href="{% url 'main:progress' %}">прогресс месяца</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item {% if request.resolver_match.url_name == 'diet'%} active {% endif%}">
            <a class="nav-link" href="{% url 'personal:index' %}">{{ user.first_name|default:'пользователь' }}</a>
          </li>
          <li class="nav-item {% if request.resolver_match.url_name == 'index'%} active {% endif%}">
            <a class="nav-link" href="{% url 'auth:logout' %}">выйти</a>
          </li>
        {% else %}
          <li class="nav-item {% if request.resolver_match.url_name == 'personal'%} active {% endif%}">
            <a class="nav-link" href="{% url 'auth:login' %}">личный кабинет</a>
          </li>
        {% endif %}
        {% if user.is_superuser %}
          <li class="nav-item {% if request.resolver_match.url_name == 'users'%} active {% endif%}">
            <a class="nav-link" href="{% url 'admin:users' %}">админка</a>
          </li>
        {% endif %}
    </ul>
  </div>
</nav>