authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
	path('update/', authapp.update, name='update'),
]    

fitness/urls.py
"""fitness URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:"""

from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('personal/', include('personalapp.urls', namespace='personal')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    #path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.contrib import admin

import mainapp.views as mainapp

app_name = 'main'

urlpatterns = [
    path('', mainapp.gallery, name='index'),
    path('gallery/', mainapp.gallery, name='gallery'),
    path('exercise/', mainapp.exercise, name='exercise'),
    path('diet/', mainapp.diet, name='diet'),
    path('progress/', mainapp.progress, name='progress'),
]

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator


phone_regex = RegexValidator(
        regex=r'^\+?7?\d{10}$',
        message="Номер телефона должен быть в формате +79998887766")


class FitnessUser(AbstractUser):
    avatar = models.ImageField(
        upload_to='users_avatars',
        null=True, blank=True
    )
    date_birth = models.DateField(
        verbose_name='дата рождения',
        null=True, blank=True
    )
    height = models.PositiveSmallIntegerField(
        verbose_name=' рост',
        null=True, blank=True
    )
    phone_number = models.CharField(
        validators=[phone_regex],
        max_length=17,
        blank=True
    )

    def __str__(self):
        return f'{ self.last_name } { self.first_name }'

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from django import forms
from authapp.models import FitnessUser


class FitnessUserLoginForm(AuthenticationForm):
    class Meta:
        model = FitnessUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(FitnessUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class FitnessUserRegisterForm(UserCreationForm):
    class Meta:
        model = FitnessUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'date_birth', 'avatar')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class FitnessUserEditForm(UserChangeForm):
    class Meta:
        model = FitnessUser
        fields = ('avatar', 'username', 'first_name', 'last_name', 'email', 'date_birth', 'password')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse


from authapp.forms import FitnessUserLoginForm
from authapp.forms import FitnessUserRegisterForm
from authapp.forms import FitnessUserEditForm


def login(request):
    next = request.GET['next'] if 'next' in request.GET.keys() else ''
    if request.method == 'POST':
        form = FitnessUserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                if 'next' in request.POST.keys():
                    return HttpResponseRedirect(request.POST['next'])
                else:
                    return HttpResponseRedirect(reverse('personal:index'))
    else:
        form = FitnessUserLoginForm()

    context = {
        'title': 'вход в систему',
        'form': form,
        'next': next
    }
    return render(request, 'authapp/login.html', context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    
    if request.method == 'POST':
        form = FitnessUserRegisterForm(request.POST, request.FILES)
    
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = FitnessUserRegisterForm()
    
    content = {
        'title': 'регистрация', 
        'form': form
        }
    
    return render(request, 'authapp/register.html', content)
    
    
def update(request):
    
    if request.method == 'POST':
        form = FitnessUserEditForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:update'))
    else:
        form = FitnessUserEditForm(instance=request.user)
    
    content = {
        'title': 'редактирование', 
        'form': form
        }
    
    return render(request, 'authapp/update.html', content)  

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-center fixed-top">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </nav>
	<div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>            
            
            {% block content %}

            {% endblock %}
        </div>
	</div>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-center fixed-bottom">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </nav>
</body>
</html>   

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
    	{% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>
    <a href="{% url 'auth:register' %}" class="btn btn-round form-control">
        зарегистрироваться
    </a>

{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>
{% endblock %}

authapp/templates/authapp/update.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <br><br><br>
    <div class="user_avatar"><img src="/media/{{ user.avatar }}"></div>
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'main:index' %}" class="">
            на главную
        </a>
    </button>

{% endblock %}