adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('trainings/', adminapp.trainings, name='trainings'),
    path('trainings/create/', adminapp.training_create, name='training_create'),
    path('trainings/update/<int:pk>/', adminapp.training_update, name='training_update'),
    path('trainings/delete/<int:pk>/', adminapp.training_delete, name='training_delete'),

    path('schedules/', adminapp.schedules, name='schedules'),
    path('schedules/create/', adminapp.schedule_create, name='schedule_create'),
    path('schedules/update/<int:pk>/', adminapp.schedule_update, name='schedule_update'),
    path('schedules/delete/<int:pk>/', adminapp.schedule_delete, name='schedule_delete'),

    path('users/read/', adminapp.users, name='users'),
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('progress/', adminapp.progress, name='progress'),
    path('messages/', adminapp.messages, name='messages'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
	path('update/', authapp.update, name='update'),
]    

fitness/urls.py
"""fitness URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:"""

from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('personal/', include('personalapp.urls', namespace='personal')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    #path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from authapp.models import FitnessUser
from authapp.forms import FitnessUserEditForm
from django import forms
from django.contrib.admin import widgets

from mainapp.models import Training, Schedule


class FitnessUserAdminEditForm(FitnessUserEditForm):
    class Meta:
        model = FitnessUser
        fields = '__all__'


class TrainingCreateForm(forms.ModelForm):
    class Meta:
        model = Training
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class TrainingEditForm(forms.ModelForm):
    class Meta:
        model = Training
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class DateInput(forms.DateInput):
    input_type = 'date'


class TimeInput(forms.TimeInput):
    input_type = 'time'


class ScheduleCreateForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['date', 'time', 'is_visit', 'training', 'fitnessuser']
        widgets = {
            'date': DateInput(),
            'time': TimeInput(),
        }


class ScheduleEditForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['date', 'time', 'is_visit', 'training', 'fitnessuser']
        widgets = {
            'date': DateInput(),
            'time': TimeInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


adminapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.utils.timezone import now

from authapp.forms import FitnessUserRegisterForm
from adminapp.forms import (FitnessUserAdminEditForm,
                            TrainingCreateForm, TrainingEditForm,
                            ScheduleCreateForm, ScheduleEditForm)
from mainapp.models import (FitnessUser, ExtractYear, Training,
                            Schedule, Message)


@user_passes_test(lambda u: u.is_superuser)
def users(request):
    year = now().isocalendar()[0]
    users_list = FitnessUser.objects.exclude(
        is_active=False).annotate(
        age=year-ExtractYear('date_birth')).order_by(
        '-is_superuser', '-is_staff', 'username'
    )
    paginator = Paginator(users_list, 3)
    page = request.GET.get('page', 1)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    context = {
        'title': 'админка/пользователи',
        'users': users,
        }

    return render(request, 'adminapp/users.html', context)


def user_create(request):

    if request.method == 'POST':
        form = FitnessUserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        form = FitnessUserRegisterForm()
    
    context = {
        'title': 'пользователи/создание', 
        'update_form': form
        }
    
    return render(request, 'adminapp/user_update.html', context)


def user_update(request, pk):

    edit_user = get_object_or_404(FitnessUser, pk=pk)
    if request.method == 'POST':
        edit_form = FitnessUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:user_update',\
                                                args=[edit_user.pk]))
    else:
        edit_form = FitnessUserAdminEditForm(instance=edit_user)
    
    context = {
        'title': 'пользователи/редактирование', 
        'update_form': edit_form
        }
    return render(request, 'adminapp/user_update.html', context)


def user_delete(request, pk):
    user = get_object_or_404(FitnessUser, pk=pk)
    
    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin:users'))

    context = {
        'title': 'пользователи/удаление', 
        'user_to_delete': user
        }
    
    return render(request, 'adminapp/user_delete.html', context)


def trainings(request):
    """ Функция для отображения тренировок """
    training_list = Training.objects.filter(is_active=True)
    paginator = Paginator(training_list, 4)
    page = request.GET.get('page', 1)
    try:
        trainings = paginator.page(page)
    except PageNotAnInteger:
        trainings = paginator.page(1)
    except EmptyPage:
        trainings = paginator.page(paginator.num_pages)

    context = {
        'trainings': trainings,
    }
    return render(request, 'adminapp/trainings.html', context)


def training_create(request):
    """ Функция для отображения формы создания новой тренировки"""
    if request.method == 'POST':
        form = TrainingCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        form = TrainingCreateForm()

    context = {
        'title': 'тренировки/создание',
        'form': form
    }
    return render(request, 'adminapp/training_create.html', context)


def training_update(request, pk):
    """ Функция для отображения формы редактирования новой тренировки"""
    edit_training = get_object_or_404(Training, pk=pk)
    if request.method == 'POST':
        form = TrainingEditForm(request.POST, request.FILES, instance=edit_training)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:training_update', \
                                                args=[edit_training.pk]))
    else:
        form = TrainingEditForm(instance=edit_training)

    context = {
        'title': 'Тренировки/редактирование',
        'form': form
    }
    return render(request, 'adminapp/training_create.html', context)


def training_delete(request, pk):
    """ Функция для отображения формы удаления новой тренировки """
    training = get_object_or_404(Training, pk=pk)

    if request.method == 'POST':
        training.is_active = False
        training.save()
        return HttpResponseRedirect(reverse('admin:trainings'))

    context = {
        'title': 'тренировки/удаление',
        'training_to_delete': training
    }

    return render(request, 'adminapp/training_delete.html', context)


def schedules(request):
    """ Функция для отображения занятий """
    schedules = Schedule.objects.order_by('-date', '-time')
    context = {
        'schedules': schedules,
    }
    return render(request, 'adminapp/schedules.html', context)


def schedule_create(request):
    """ Функция для отображения формы создания нового занятия"""
    if request.method == 'POST':
        form = ScheduleCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:schedules'))
    else:
        form = ScheduleCreateForm()

    context = {
        'title': 'занятие/создание',
        'form': form
    }
    return render(request, 'adminapp/schedule_create.html', context)


def schedule_update(request, pk):
    """ Функция для отображения формы редактирования нового занятия"""
    edit_schedule = get_object_or_404(Schedule, pk=pk)
    if request.method == 'POST':
        form = ScheduleEditForm(request.POST, request.FILES, instance=edit_schedule)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:schedule_update', \
                                                args=[edit_schedule.pk]))
    else:
        form = ScheduleEditForm(instance=edit_schedule)

    context = {
        'title': 'Занятия/редактирование',
        'form': form
    }
    return render(request, 'adminapp/schedule_create.html', context)


def schedule_delete(request, pk):
    """ Функция для отображения формы удаления нового занятия"""
    schedule = get_object_or_404(Schedule, pk=pk)

    if request.method == 'POST':
        schedule.delete()
        return HttpResponseRedirect(reverse('admin:schedules'))

    context = {
        'title': 'занятия/удаление',
        'schedule_to_delete': schedule
    }

    return render(request, 'adminapp/schedule_delete.html', context)


def progress(request):
    """ Функция для отображения графика прогресса тренирующихся"""
    context = {}
    return render(request, 'adminapp/results.html', context)


def messages(request):
    """ Функция для отображения сообщений из личных кабинетов тренирующихся"""
    message_list = Message.objects.order_by("-timestamp")
    paginator = Paginator(message_list, 4)
    page = request.GET.get('page', 1)
    try:
        messages = paginator.page(page)
    except PageNotAnInteger:
        messages = paginator.page(1)
    except EmptyPage:
        messages = paginator.page(paginator.num_pages)

    context = {
        'title': 'сообщения',
        'messages': messages,
    }
    return render(request, 'adminapp/messages.html', context)

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {{ form.media }}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-center fixed-top">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </nav>
    <div class="container">
  	    <div class="row">
            <div class="col-md2">
            {% include 'adminapp/includes/inc__admin_menu.html' %}
            </div>
            <div class="col-md2">

            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-center fixed-bottom">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </nav>
<script>
    var django = django || {};
    django.jQuery = $;
</script>
</body>
</html>

adminapp/templates/adminapp/messages.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <br><br><br>
<div class="container h-100">
  <div>
        {% for message in messages %}
            <div>
                <img class="rounded-circle" src="{{ MEDIA_URL }}{{ message.fitnessuser.avatar }}" width='90'
                     height='70' alt=''>
                {{ message.fitnessuser }}
                {{ message.timestamp }}
                {{ message.fitnessuser.email }}
                {{ message.fitnessuser.phone_number }}
            </div>
            <div>
              {{ message.body }}
            </div>
        {% endfor %}
  </div>
</div>
<div class="container">
  <div class="row justify-content-center align-items-center">
        {% if messages.has_other_pages %}
          <ul class="pagination">
            {% if messages.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ messages.previous_page_number }}">Предыдущая</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                  <a class="page-link"><span>Предыдущая</span></a>
              </li>
            {% endif %}
            {% for i in messages.paginator.page_range %}
              {% if messages.number == i %}
                  <li class="page-item active">
                      <a class="page-link"><span>{{ i }}</span></a><span class="sr-only">(current)</span>
                  </li>
              {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
              {% endif %}
            {% endfor %}
            {% if messages.has_next %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ messages.next_page_number }}">Следущая</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                  <a class="page-link"><span>Следущая</span></a>
              </li>
            {% endif %}
          </ul>
        {% endif %}
  </div>
</div>

  <br><br><br>
{% endblock %}

adminapp/templates/adminapp/results.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <br><br><br>
<div class="container h-100">
  <div class="row h-100 justify-content-center align-items-center">
        Здесь будут результаты тренирующихся
  </div>
</div>
{% endblock %}

adminapp/templates/adminapp/schedule_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <br><br><br>
<div class="container h-100">
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:schedules' %}">
      к списку занятий
    </a>
  </button>
  </div>

{% endblock %}

adminapp/templates/adminapp/schedule_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <br><br><br>
  <div class="user_delete">
    Уверены, что хотите удалить {{ schedule_to_delete.desc }}
      {{ schedule_to_delete.is_visit }} {{ schedule_to_delete.date }} {{ schedule_to_delete.time }}
      {{ schedule_to_delete.training }} {{ schedule_to_delete.fitnessuser }}
    ?
    <form action="{% url 'admin:schedule_delete' schedule_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:schedules' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/schedules.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <br><br><br>
<div class="container h-100">
  <div class="row h-100 justify-content-center align-items-center">
    <dl class="dl-horizontal">
        <dt>
          <button type="button" class="btn btn-outline-primary">
            <a href="{% url 'admin:schedule_create' %}"> новое занятие </a>
          </button>
        </dt><dd></dd>
        {% for schedule in schedules %}
        <dt>
            <div>
                <p>
                    {{ schedule.date }} {{ schedule.time }}
                    {{ schedule.is_visit }}{{ schedule.fitnessuser }}
                    {{ schedule.training }}
                </p>
              <button type="button" class="btn btn-outline-primary">
                  <a href="{% url 'admin:schedule_update' schedule.pk %}">
                  редактировать
                </a>
              </button>
              <button type="button" class="btn btn-outline-primary">
                <a href="{% url 'admin:schedule_delete' schedule.pk %}">
                  удалить
                </a>
              </button>
            </div>
        </dt>
        <dd>
   {% endfor%}
    </dl>
    </div>
  </div>
{% endblock %}

adminapp/templates/adminapp/training_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <br><br><br>
<div class="container h-100">
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_table }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:trainings' %}">
      к списку тренировок
    </a>
  </button>
  </div>
</div>
{% endblock %}

adminapp/templates/adminapp/training_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <br><br><br>
  <div class="user_delete">
    Уверены, что хотите удалить {{ training_to_delete.desc }}
    {% if training_to_delete.short_desc %}
      ({{ training_to_delete.desc|title }}</b>
      {% if training_to_delete.short_desc %}
        {{ training_to_delete.short_desc|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin:training_delete' training_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:trainings' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/trainings.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <br><br><br>
    <div class="dl-horizontal">
            <button class="btn btn-outline-primary">
              <a href="{% url 'admin:training_create' %}"> новая тренировка </a>
            </button>
        {% for training in trainings %}
            <p class="col-5">
                {{ training.short_desc|title }}
                {{ training.desc|title }}
            </p>
            <button class="btn btn-outline-primary"> <a href="{% url 'admin:training_update' training.pk %}">
                редактировать
              </a>
            </button>
            <button class="btn btn-outline-primary">
              <a href="{% url 'admin:training_delete' training.pk %}">
                удалить
              </a>
            </button>
        {% endfor%}
    </div>

    <div class="container">
      <div class="row justify-content-center align-items-center">
            {% if trainings.has_other_pages %}
              <ul class="pagination">
                {% if trainings.has_previous %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ trainings.previous_page_number }}">Предыдущая</a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                      <a class="page-link"><span>Предыдущая</span></a>
                  </li>
                {% endif %}
                {% for i in trainings.paginator.page_range %}
                  {% if trainings.number == i %}
                      <li class="page-item active">
                          <a class="page-link"><span>{{ i }}</span></a><span class="sr-only">(current)</span>
                      </li>
                  {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                  {% endif %}
                {% endfor %}
                {% if trainings.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ trainings.next_page_number }}">Следущая</a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                      <a class="page-link"><span>Следущая</span></a>
                  </li>
                {% endif %}
              </ul>
            {% endif %}
      </div>
    </div>

  <br><br><br>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ user_to_delete.username }} 
    {% if user_to_delete.first_name %}
      ({{ user_to_delete.first_name|title }}</b>
      {% if user_to_delete.last_name %}
        {{ user_to_delete.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin:user_delete' user_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:users' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <br><br><br>
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:users' %}">
      к списку пользователей
    </a>
  </button>
  <br><br><br><br><br><br>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <br><br><br>
    <div class="dl-horizontal">
          <button type="button" class="btn btn-outline-primary">
            <a href="{% url 'admin:user_create' %}"> новый пользователь </a>
          </button>
        {% for user in users %}
        <div>
            <p><img class="rounded-circle" src="{{ MEDIA_URL }}{{ user.avatar|default:'users_avatars/default.jpg' }}"
                    height="70" width="70" alt="{{ user.username }}">
                 <div>
                     <div>
                         <p> {% if user.first_name %} {{ user.first_name|title }} {% endif %}
                            {% if user.last_name %} {{ user.last_name|title }} {% endif %}
                         </p>
                     </div>
                    <div class="user_age"> возраст:{{ user.age }} лет </div>
                    <div class="user_email"> email:{{ user.email }} </div>
                    <div class="user_lastlogin"> последний раз был(а):{{ user.last_login }} </div>
                 </div>
                 {% if user.is_superuser %} администратор {% else %} пользователь {% endif %}
                  <button type="button" class="btn btn-outline-primary">
                      <a href="{% url 'admin:user_update' user.pk %}">
                      редактировать
                    </a>
                  </button>
                  <button type="button" class="btn btn-outline-primary">
                    <a href="{% url 'admin:user_delete' user.pk %}">
                      удалить
                    </a>
                  </button>
            </p>
        </div>
        {% endfor%}
    </div>

    <div class="container">
      <div class="row justify-content-center align-items-center">
            {% if users.has_other_pages %}
              <ul class="pagination">
                {% if users.has_previous %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ users.previous_page_number }}">Предыдущая</a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                      <a class="page-link"><span>Предыдущая</span></a>
                  </li>
                {% endif %}
                {% for i in users.paginator.page_range %}
                  {% if users.number == i %}
                      <li class="page-item active">
                          <a class="page-link"><span>{{ i }}</span></a><span class="sr-only">(current)</span>
                      </li>
                  {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                  {% endif %}
                {% endfor %}
                {% if users.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ users.next_page_number }}">Следущая</a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                      <a class="page-link"><span>Следущая</span></a>
                  </li>
                {% endif %}
              </ul>
            {% endif %}
      </div>
    </div>
  <br><br><br>
{% endblock %}